In [14]:
import numpy as np
import matplotlib.pyplot as plt

a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
a.ndim #Imprime el numero de dimensiones de un array
a.shape
a.size

a[1,2] #Fila, Columna
a[1][2]

a[0][0:2] # Primeros dos valores de la primera fila
a[0:2,2] # Primeros dos valores de la ultima columna



array([13, 23])

In [15]:
add_x = np.array([[1,0],[0,1]])
add_y = np.array([[2,1],[1,2]])

Z = add_x + add_y
Z

addition = np.add(add_x,add_y)
addition

array([[3, 1],
       [1, 3]])

In [21]:
multi_Y = np.array([[2,1],[1,2]])
number = 4

Z = number * multi_Y
Z

multiplication_scalar = np.multiply(multi_Y,number)
multiplication_scalar

multi_X = np.array([[5,3],[3,5]])
multip = np.multiply(multi_Y,multi_X)
multip

result = multi_Y * multi_X
result

array([[10,  3],
       [ 3, 10]])

In [23]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

Z = np.dot(A,B)
Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [27]:
#Transpuesta

C = np.array([[1,1],[2,2],[3,3]])
C.T


array([[1, 2, 3],
       [1, 2, 3]])